// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	dtos "happyBill/dtos"
	models "happyBill/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateBillboard mocks base method.
func (m *MockRepository) CreateBillboard(product models.Product) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBillboard", product)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBillboard indicates an expected call of CreateBillboard.
func (mr *MockRepositoryMockRecorder) CreateBillboard(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBillboard", reflect.TypeOf((*MockRepository)(nil).CreateBillboard), product)
}

// CreateClient mocks base method.
func (m *MockRepository) CreateClient(client models.User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", client)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockRepositoryMockRecorder) CreateClient(client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockRepository)(nil).CreateClient), client)
}

// CreateManager mocks base method.
func (m *MockRepository) CreateManager(manager models.User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManager", manager)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManager indicates an expected call of CreateManager.
func (mr *MockRepositoryMockRecorder) CreateManager(manager interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManager", reflect.TypeOf((*MockRepository)(nil).CreateManager), manager)
}

// DeleteBillboard mocks base method.
func (m *MockRepository) DeleteBillboard(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBillboard", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBillboard indicates an expected call of DeleteBillboard.
func (mr *MockRepositoryMockRecorder) DeleteBillboard(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBillboard", reflect.TypeOf((*MockRepository)(nil).DeleteBillboard), id)
}

// GetAllBillboards mocks base method.
func (m *MockRepository) GetAllBillboards(page int) ([]dtos.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBillboards", page)
	ret0, _ := ret[0].([]dtos.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBillboards indicates an expected call of GetAllBillboards.
func (mr *MockRepositoryMockRecorder) GetAllBillboards(page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBillboards", reflect.TypeOf((*MockRepository)(nil).GetAllBillboards), page)
}

// GetAllManagers mocks base method.
func (m *MockRepository) GetAllManagers(page int) ([]dtos.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllManagers", page)
	ret0, _ := ret[0].([]dtos.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllManagers indicates an expected call of GetAllManagers.
func (mr *MockRepositoryMockRecorder) GetAllManagers(page interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllManagers", reflect.TypeOf((*MockRepository)(nil).GetAllManagers), page)
}

// GetBillboardById mocks base method.
func (m *MockRepository) GetBillboardById(id int) (dtos.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBillboardById", id)
	ret0, _ := ret[0].(dtos.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBillboardById indicates an expected call of GetBillboardById.
func (mr *MockRepositoryMockRecorder) GetBillboardById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBillboardById", reflect.TypeOf((*MockRepository)(nil).GetBillboardById), id)
}

// GetManagerById mocks base method.
func (m *MockRepository) GetManagerById(id int) (dtos.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagerById", id)
	ret0, _ := ret[0].(dtos.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManagerById indicates an expected call of GetManagerById.
func (mr *MockRepositoryMockRecorder) GetManagerById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagerById", reflect.TypeOf((*MockRepository)(nil).GetManagerById), id)
}

// GetRoleId mocks base method.
func (m *MockRepository) GetRoleId(role string, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleId", role, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleId indicates an expected call of GetRoleId.
func (mr *MockRepositoryMockRecorder) GetRoleId(role, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleId", reflect.TypeOf((*MockRepository)(nil).GetRoleId), role, userId)
}

// GetRoles mocks base method.
func (m *MockRepository) GetRoles(id int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockRepositoryMockRecorder) GetRoles(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockRepository)(nil).GetRoles), id)
}

// GetUser mocks base method.
func (m *MockRepository) GetUser(username string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", username)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockRepositoryMockRecorder) GetUser(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockRepository)(nil).GetUser), username)
}

// UpdateBillboard mocks base method.
func (m *MockRepository) UpdateBillboard(id int, input models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBillboard", id, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBillboard indicates an expected call of UpdateBillboard.
func (mr *MockRepositoryMockRecorder) UpdateBillboard(id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBillboard", reflect.TypeOf((*MockRepository)(nil).UpdateBillboard), id, input)
}
