basePath: /
definitions:
  dtos.SignInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      surname:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - surname
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server for order billboards.
  title: HappyBill
  version: "1.0"
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login to account
      operationId: login-account
      parameters:
      - description: username / password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dtos.SignInRequest'
      produces:
      - application/json
      responses: {}
      summary: Sign In
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: register to site
      operationId: create-account
      parameters:
      - description: username / email / password / name / surname
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses: {}
      summary: Sign Up
      tags:
      - auth
swagger: "2.0"
